---
name: Publish

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions: read-all

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment variables
        id: setvars
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          echo "GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_ENV"
          echo "IMAGE_BASE=$(sed -Ene 's/^[[:space:]]*from[[:space:]]*([^[:space:]]+).*$/\1/Ip' < Dockerfile)" >> "$GITHUB_ENV"
          #          sudo apt-get install -fy jq curl
          echo "DESCRIPTION=$(curl -q "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY#*/}" | jq -r '.description')" >> "$GITHUB_ENV"


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
          registry: registry.hub.docker.com

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ github.event.repository.name }}:edge
            registry.hub.docker.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:edge
          labels: |
            org.opencontainers.image.created=${{ env.DATE }}
            org.opencontainers.image.authors=${{ secrets.GHCR_USERNAME }}
            org.opencontainers.image.url=${{ github.server_url }}/${{ env.GITHUB_REPOSITORY }}
            org.opencontainers.image.documentation=${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/blob/${{ env.GIT_BRANCH }}/README.md
            org.opencontainers.image.source=${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}
            org.opencontainers.image.revision=${{ env.GITHUB_REF }}
            org.opencontainers.image.base.name=${{ env.IMAGE_BASE }}
            org.opencontainers.image.description=${{ env.DESCRIPTION }}

      - name: update DockerHub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

      - name: update SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ github.event.repository.name }}:latest
          registry-username: ${{ secrets.GHCR_USERNAME }}
          registry-password: ${{ secrets.GHCR_PAT }}
          artifact-name: sbom.spdx
